from collections import deque

queue = deque()

queue.append(10)
queue.append(20)
queue.append(30)
queue.append(40)
queue.append(50)
print(f"Queue: {list(queue)}")
# queue.popleft()
# queue.popleft()
# queue.popleft()
# queue.popleft()
# queue.popleft()
# queue.append(60)
# print(f"Queue: {list(queue)}")
print(f"Front: {queue[0]}")
print(f"Rare: {queue[-1]}")
print(f"Is Empty: {not queue}")